@echo off
echo [1] 포트 3307 점유 프로세스 확인 중...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr ":3307 " ^| findstr "LISTENING"') do (
    echo     PID %%a 종료 중...
    taskkill /F /PID %%a >nul 2>&1
)
echo [2] 2초 대기...
timeout /t 2 /nobreak >nul
echo [3] 백엔드 시작...
call gradlew.bat bootRun
